services:

  ccf-sandbox:
    build:
      dockerfile: Dockerfile.ccf-sandbox
    command: |
      /bin/bash -c '
        rm -rf /workspace/sandbox*
        /opt/ccf_virtual/bin/sandbox.sh --http2 \
          --initial-member-count 1 \
          --initial-user-count 1 &
        while [ ! -f /workspace/sandbox_common/user0_cert.pem ]; do
          sleep 1
        done
        cp /workspace/sandbox_common/*.pem /workspace/
        sleep infinity
      '
    network_mode: host
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -k -s -f https://localhost:8000/node/state && test -f /workspace/sandbox_common/user0_cert.pem"
      ]
      interval: 1s
      retries: 120
    volumes:
      - ${KMS_WORKSPACE}:/workspace

  jwt-issuer:
    build:
      context: test/utils/jwt
      dockerfile: Dockerfile.jwt-issuer
    command: node dist/index.js
    network_mode: host
    environment:
      - KMS_WORKSPACE=/workspace
      - JWT_ISSUER_PORT=${JWT_ISSUER_PORT:-}
    healthcheck:
      test: "curl -k --fail -X POST $(cat /workspace/jwt_issuer_address)/token"
      interval: 1s
      retries: 120
    volumes:
      - ${JWT_ISSUER_WORKSPACE}:/workspace
