name: Daily

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  ci:
    secrets: inherit
    uses: ./.github/workflows/ci.yml
