name: Test Orchestrator

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:

  test-orchestrator:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          # Use a managed identity to authenticate to Azure
          # Use properties such as client-id, tenant-id, and subscription-id in the secrets and vars
          # The managed identity should have a federated credential with subject identiier repo:<organization>/<repo>:pull_request
          # Use subject identifier repo:<organization>/<repo>:ref:refs/heads/<branch> for running manual CI's
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Dependencies
        run: pip install -r scripts/ccf/az-cleanroom-aci/orchestrator/requirements.txt

      - name: Test Orchestrator
        run: pytest -sv scripts/ccf/az-cleanroom-aci/orchestrator/test/test.py

      - name: Print Orchestrator Logs
        if: always()
        run: docker compose -p orchestrator logs
